import {BookIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const catalogue = defineType({
  name: 'catalogue',
  title: 'Catalogue',
  type: 'document',
  icon: BookIcon,
  groups: [
    { name: 'general', title: 'General' },
    { name: 'media', title: 'Media' },
    { name: 'relationships', title: 'Relationships' },
    { name: 'filters', title: 'Catalogue Filters' },
    { name: 'cta', title: 'Call to Action' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'mainHeading',
      title: 'Main Heading',
      type: 'string',
      description: 'Used for the main title.',
      group: 'general',
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string',
      description: 'Used for the bold italic text below the main title.',
      group: 'general',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      group: 'general',
    }),
    defineField({
      name: 'bottomTags',
      title: 'Bottom Tags',
      type: 'string',
      description: 'Used for the small uppercase tags at the bottom of the hero (e.g. PRIVATE LABEL / DEVELOPMENT).',
      group: 'general',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
    }),
    defineField({
      name: 'productLines',
      title: 'Product Lines / Categories',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'productLine' }] }],
      group: 'relationships',
      description: 'The product lines available in this catalogue.',
    }),
    // Catalogue-level filter configurations
    defineField({
      name: 'filterCategory',
      title: 'Category Filters',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'filterOption' }] }],
      group: 'filters',
    }),
    defineField({
      name: 'filterProductType',
      title: 'Product Type Filters',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'filterOption' }] }],
      group: 'filters',
    }),
    defineField({
      name: 'filterGenderFit',
      title: 'Gender / Fit Filters',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'filterOption' }] }],
      group: 'filters',
    }),
    defineField({
      name: 'filterFabricDescription',
      title: 'Fabric Description Filters',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'filterOption' }] }],
      group: 'filters',
    }),
    defineField({
      name: 'filterConstruction',
      title: 'Construction Filters',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'filterOption' }] }],
      group: 'filters',
    }),
    defineField({
      name: 'centerText',
      title: 'Center Text',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaEyebrow',
      title: 'CTA Eyebrow',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaHeadingLine1',
      title: 'CTA Heading Line 1',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaHeadingLine2',
      title: 'CTA Heading Line 2',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaDescription',
      title: 'CTA Description',
      type: 'text',
      group: 'cta',
    }),
    defineField({
      name: 'ctaButtonText',
      title: 'CTA Button Text',
      type: 'string',
      group: 'cta',
    }),
    defineField({
      name: 'ctaButtonLink',
      title: 'CTA Button Link',
      type: 'url',
      description: 'E.g., /contact or https://...',
      group: 'cta',
      validation: (Rule) => Rule.uri({ allowRelative: true }),
    }),
    defineField({
      name: 'seo',
      title: 'SEO Settings',
      type: 'seoMetaFields',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'heroImage',
    },
  },
})
