import {CubeIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const product = defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  icon: CubeIcon,
  groups: [
    { name: 'general', title: 'General' },
    { name: 'media', title: 'Media' },
    { name: 'relationships', title: 'Relationships' },
    { name: 'attributes', title: 'Attributes / Filters' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'productCode',
      title: 'Product Code / SKU',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      group: 'general',
    }),
    defineField({
      name: 'thumbnailImage',
      title: 'Thumbnail Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
      description: 'Used for product cards and grid listings. Falls back to Main Image if empty.',
    }),
    defineField({
      name: 'mainImage',
      title: 'Main Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      group: 'media',
    }),
    defineField({
      name: 'productLine',
      title: 'Product Line',
      type: 'reference',
      to: [{ type: 'productLine' }],
      group: 'relationships',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'productFamily',
      title: 'Product Family',
      type: 'reference',
      to: [{ type: 'productFamily' }],
      group: 'relationships',
      validation: (Rule) => Rule.required(),
    }),
    // Attributes / Filters for this specific product
    /*defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),*/
    defineField({
      name: 'productType',
      title: 'Product Type',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'genderFit',
      title: 'Gender / Fit',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'fabricDescription',
      title: 'Fabric Description',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'construction',
      title: 'Construction',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'type',
      title: 'Type',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'wire',
      title: 'Wire / Non-Wire',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'padding',
      title: 'Padding',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'support',
      title: 'Support',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'cupRange',
      title: 'Cup Range',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'fabric',
      title: 'Fabric',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'seo',
      title: 'SEO Settings',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'productCode',
      media: 'mainImage',
    },
  },
})
