import {ComponentIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const productFamily = defineType({
  name: 'productFamily',
  title: 'Product Family',
  type: 'document',
  icon: ComponentIcon,
  groups: [
    { name: 'general', title: 'General' },
    { name: 'media', title: 'Media' },
    { name: 'relationships', title: 'Relationships' },
    { name: 'attributes', title: 'Product Family Attributes' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      group: 'general',
    }),
    defineField({
      name: 'mainHeading',
      title: 'Main Heading',
      type: 'string',
      description: 'Used for the main title.',
      group: 'general',
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string',
      description: 'Used for the bold italic text below the main title.',
      group: 'general',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      group: 'general',
    }),
    defineField({
      name: 'bottomTags',
      title: 'Bottom Tags',
      type: 'string',
      description: 'Used for the small uppercase tags at the bottom of the hero (e.g. PRIVATE LABEL / DEVELOPMENT).',
      group: 'general',
    }),
    defineField({
      name: 'thumbnailImage',
      title: 'Thumbnail Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
    }),
    defineField({
      name: 'productLine',
      title: 'Product Line',
      type: 'reference',
      to: [{ type: 'productLine' }],
      group: 'relationships',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'products',
      title: 'Products',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'product' }] }],
      group: 'relationships',
      description: 'The individual products belonging to this family.',
    }),
    // Product Family Attributes (Actual values for the products in this family)
    defineField({
      name: 'attrWire',
      title: 'Wire / Non-Wire',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'attrPadding',
      title: 'Padding',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'attrCupRange',
      title: 'Cup Range',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'attrSupport',
      title: 'Support Level',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'attrFabric',
      title: 'Fabric',
      type: 'reference',
      to: [{ type: 'filterOption' }],
      group: 'attributes',
    }),
    defineField({
      name: 'seo',
      title: 'SEO Settings',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'productLine.title',
      media: 'heroImage',
    },
  },
})
